<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>preview</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="WolverineFx" />
    <PackageReference Include="Marten" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Core\Core.csproj" />
    <ProjectReference Include="..\..\Abstractions\AuthKit.Plugins.Abstractions.csproj" />
  </ItemGroup>
</Project>
